version: '3.8'

services:
  moments-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moments-go-bot-prod
    restart: always
    environment:
      # Telegram 配置
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
      # GitHub 配置
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GITHUB_FILE_REPO=${GITHUB_FILE_REPO:-static}
    volumes:
      # 挂载日志目录
      - ./logs:/app/logs
    networks:
      - moments-network
    # 生产环境健康检查
    healthcheck:
      test: ["CMD", "pgrep", "moments-go"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 60s
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  moments-network:
    driver: bridge 
